@props(['num'])
@ref ('count', $num)

<script setup>

    import { computed, inject, ref, onMounted } from 'vue'

    onMounted(() => {
        console.log('On mounted')
    })

    const $bridge = inject('$bridge');

    console.log($bridge.version);

    const props = defineProps(['msg']);

    console.log(props);

    const Product = computed(() => num.value);


    const click = () => num.value++;

    const num = ref(
        @data('num')
    );

    const count = computed(() => num.value + 1);

</script>

<slot name="juana"></slot>

<h1>{{ msg }}</h1>

{{ count }}

<div class="card">
    <button type="button" @click="click">count</button>
    <p>
        {{ Product }}
        Edit
        <code>components/HelloWorld.vue</code> to test HMR
        <hr>
        {{ num }}
    </p>
</div>

<p>
    Check out
    <a href="https://vuejs.org/guide/quick-start.html#local" target="_blank">create-vue</a>, the official Vue + Vite
    starter
</p>
<p>
    Install
    <a href="https://github.com/vuejs/language-tools" target="_blank">Volar</a>
    in your IDE for a better DX
</p>
<p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>