@extends ([
'layaut',
'asdas'
], (sss))

@section('content')
<section>
    {{ str < 5 | uppercase (asda) }}

    <Tuhermana />
</section>

<div @probadoinnerdirective (5 < 4) style="border:1px solid red;">
    dividasd
    <component-prueba @tuPuta pedro="{{ juena }}" hola="probando asdas">
        <component-inner>
            probando inner component
        </component-inner>
    </component-prueba>

    <p>
        hola
    </p>

</div>
@@yield('hola')

hola probando
@endsection